#
# Build stage
#
FROM maven:3.9.9-eclipse-temurin-17-alpine AS build
COPY pom.xml /home/app/pom.xml
COPY umpoint/pom.xml /home/app/umpoint/pom.xml
COPY umpoint/umpoint-application/pom.xml /home/app/umpoint/umpoint-application/pom.xml
# Download Maven dependencies (this step will be cached as long as the pom.xml files don't change)
RUN mvn -f /home/app/umpoint/umpoint-application/pom.xml dependency:go-offline -B

COPY umpoint/umpoint-application /home/app/umpoint/umpoint-application
RUN mvn -f /home/app/umpoint/umpoint-application/pom.xml clean package

#
# Package stage
#
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
EXPOSE 8080
COPY --from=build /home/app/umpoint/umpoint-application/target/umpoint-application.jar /app/umpoint-application.jar
CMD ["java", "-jar", "/app/umpoint-application.jar"]